repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.392.post0
    hooks:
    - id: pyright
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
